export const filters = [
  {
    id: 'Product Group',
    name: 'Product Group',
    options: [
      { value: '', label: 'All', checked: false },
      { value: '113', label: 'Allo KSA', checked: false },
      { value: '24', label: 'Amazon US', checked: false },
      { value: '133', label: 'Ananas', checked: false },
      { value: '1', label: 'Apple Card US', checked: false },
      { value: '114', label: 'Apple iTunes KSA', checked: false },
      { value: '193', label: 'App Store & iTunes US', checked: false },
      { value: '170', label: 'Binance', checked: false },
      { value: '52', label: 'CardPlus', checked: false },
      { value: '115', label: 'CashU Card', checked: false },
      { value: '195', label: 'CryptoVoucher', checked: false },
      { value: '3', label: 'Flexepin CAD', checked: false },
      { value: '117', label: 'Friendi', checked: false },
      { value: '2', label: 'Google Play USA', checked: false },
      { value: '198', label: 'Hypermarket', checked: false },
      { value: '26', label: 'IMVU', checked: false },
      { value: '21', label: 'iTunes UK', checked: false },
      { value: '98', label: 'Jaxon', checked: false },
      { value: '118', label: 'Lebara Voice KSA', checked: false },
      { value: '120', label: 'Mobily Data', checked: false },
      { value: '119', label: 'Mobily KSA', checked: false },
      { value: '175', label: 'Mowruz', checked: false },
      { value: '28', label: 'Nintendo', checked: false },
      { value: '130', label: 'Noon KSA', checked: false },
      { value: '168', label: 'Paykasa', checked: false },
      { value: '4', label: 'PSN', checked: false },
      { value: '192', label: 'River', checked: false },
      { value: '199', label: 'Shop', checked: false },
      { value: '129', label: 'Soche', checked: false },
      { value: '122', label: 'STC', checked: false },
      { value: '25', label: 'Steam USA', checked: false },
      { value: '111', label: 'Test E1', checked: false },
      { value: '197', label: 'TestRedeemableGroup', checked: false },
      { value: '140', label: 'touchEcard', checked: false },
      { value: '5', label: 'VAD', checked: false },
      { value: '100', label: 'Virgin KSA', checked: false },
      { value: '141', label: 'Voucher', checked: false },
      { value: '190', label: 'Voucherrry', checked: false },
      { value: '150', label: 'Wine', checked: false },
      { value: '6', label: 'Xbox', checked: false },
      { value: '99', label: 'Zain', checked: false },
      { value: '109', label: 'Zain Data', checked: false },
    ],
  },
  {
    id: 'Activation Region',
    name: 'Activation Region',
    options: [
      { value: '', label: 'All', checked: false },
      { value: '1', label: 'Afghanistan', checked: false },
      { value: '2', label: 'Åland Islands', checked: false },
      { value: '3', label: 'Albania', checked: false },
      { value: '4', label: 'Algeria', checked: false },
      { value: '5', label: 'American Samoa', checked: false },
      { value: '6', label: 'Andorra', checked: false },
      { value: '7', label: 'Angola', checked: false },
      { value: '8', label: 'Anguilla', checked: false },
      { value: '9', label: 'Antarctica', checked: false },
      { value: '10', label: 'Antigua & Barbuda', checked: false },
      { value: '11', label: 'Argentina', checked: false },
      { value: '12', label: 'Armenia', checked: false },
      { value: '13', label: 'Aruba', checked: false },
      { value: '14', label: 'Australia', checked: false },
      { value: '15', label: 'Austria', checked: false },
      { value: '16', label: 'Azerbaijan', checked: false },
      { value: '17', label: 'Bahamas', checked: false },
      { value: '18', label: 'Bahrain', checked: false },
      { value: '19', label: 'Bangladesh', checked: false },
      { value: '20', label: 'Barbados', checked: false },
      { value: '21', label: 'Belarus', checked: false },
      { value: '22', label: 'Belgium', checked: false },
      { value: '23', label: 'Belize', checked: false },
      { value: '24', label: 'Benin', checked: false },
      { value: '25', label: 'Bermuda', checked: false },
      { value: '26', label: 'Bhutan', checked: false },
      { value: '27', label: 'Bolivia', checked: false },
      { value: '28', label: 'Bosnia & Herzegovina', checked: false },
      { value: '29', label: 'Botswana', checked: false },
      { value: '30', label: 'Bouvet Island', checked: false },
      { value: '31', label: 'Brazil', checked: false },
      { value: '32', label: 'British Virgin Islands', checked: false },
      { value: '33', label: 'British Indian Ocean Territory', checked: false },
      { value: '34', label: 'Brunei', checked: false },
      { value: '35', label: 'Bulgaria', checked: false },
      { value: '36', label: 'Burkina Faso', checked: false },
      { value: '37', label: 'Burundi', checked: false },
      { value: '38', label: 'Cambodia', checked: false },
      { value: '39', label: 'Cameroon', checked: false },
      { value: '40', label: 'Canada', checked: false },
      { value: '41', label: 'Cape Verde', checked: false },
      { value: '42', label: 'Cayman Islands', checked: false },
      { value: '43', label: 'Central African Republic', checked: false },
      { value: '44', label: 'Chad', checked: false },
      { value: '45', label: 'Chile', checked: false },
      { value: '46', label: 'China', checked: false },
      { value: '47', label: 'Hong Kong SAR China', checked: false },
      { value: '48', label: 'Macau SAR China', checked: false },
      { value: '49', label: 'Christmas Island', checked: false },
      { value: '50', label: 'Cocos (Keeling) Islands', checked: false },
      { value: '51', label: 'Colombia', checked: false },
      { value: '52', label: 'Comoros', checked: false },
      { value: '53', label: 'Congo - Brazzaville', checked: false },
      { value: '54', label: 'Congo - Kinshasa', checked: false },
      { value: '55', label: 'Cook Islands', checked: false },
      { value: '56', label: 'Costa Rica', checked: false },
      { value: '57', label: 'Côte d’Ivoire', checked: false },
      { value: '58', label: 'Croatia', checked: false },
      { value: '59', label: 'Cuba', checked: false },
      { value: '60', label: 'Cyprus', checked: false },
      { value: '61', label: 'Czech Republic', checked: false },
      { value: '62', label: 'Denmark', checked: false },
      { value: '63', label: 'Djibouti', checked: false },
      { value: '64', label: 'Dominica', checked: false },
      { value: '65', label: 'Dominican Republic', checked: false },
      { value: '66', label: 'Ecuador', checked: false },
      { value: '67', label: 'Egypt', checked: false },
      { value: '68', label: 'El Salvador', checked: false },
      { value: '69', label: 'Equatorial Guinea', checked: false },
      { value: '70', label: 'Eritrea', checked: false },
      { value: '71', label: 'Estonia', checked: false },
      { value: '72', label: 'Ethiopia', checked: false },
      { value: '73', label: 'Falkland Islands', checked: false },
      { value: '74', label: 'Faroe Islands', checked: false },
      { value: '75', label: 'Fiji', checked: false },
      { value: '76', label: 'Finland', checked: false },
      { value: '77', label: 'France', checked: false },
      { value: '78', label: 'French Guiana', checked: false },
      { value: '79', label: 'French Polynesia', checked: false },
      { value: '80', label: 'French Southern Territories', checked: false },
      { value: '81', label: 'Gabon', checked: false },
      { value: '82', label: 'Gambia', checked: false },
      { value: '83', label: 'Georgia', checked: false },
      { value: '84', label: 'Germany', checked: false },
      { value: '85', label: 'Ghana', checked: false },
      { value: '86', label: 'Gibraltar', checked: false },
      { value: '87', label: 'Greece', checked: false },
      { value: '88', label: 'Greenland', checked: false },
      { value: '89', label: 'Grenada', checked: false },
      { value: '90', label: 'Guadeloupe', checked: false },
      { value: '91', label: 'Guam', checked: false },
      { value: '92', label: 'Guatemala', checked: false },
      { value: '93', label: 'Guernsey', checked: false },
      { value: '94', label: 'Guinea', checked: false },
      { value: '95', label: 'Guinea-Bissau', checked: false },
      { value: '96', label: 'Guyana', checked: false },
      { value: '97', label: 'Haiti', checked: false },
      { value: '98', label: 'Heard & McDonald Islands', checked: false },
      { value: '99', label: 'Vatican City', checked: false },
      { value: '100', label: 'Honduras', checked: false },
      { value: '101', label: 'Hungary', checked: false },
      { value: '102', label: 'Iceland', checked: false },
      { value: '103', label: 'India', checked: false },
      { value: '104', label: 'Indonesia', checked: false },
      { value: '105', label: 'Iran', checked: false },
      { value: '106', label: 'Iraq', checked: false },
      { value: '107', label: 'Ireland', checked: false },
      { value: '108', label: 'Isle of Man', checked: false },
      { value: '109', label: 'Israel', checked: false },
      { value: '110', label: 'Italy', checked: false },
      { value: '111', label: 'Jamaica', checked: false },
      { value: '112', label: 'Japan', checked: false },
      { value: '113', label: 'Jersey', checked: false },
      { value: '114', label: 'Jordan', checked: false },
      { value: '115', label: 'Kazakhstan', checked: false },
      { value: '116', label: 'Kenya', checked: false },
      { value: '117', label: 'Kiribati', checked: false },
      { value: '118', label: 'North Korea', checked: false },
      { value: '119', label: 'South Korea', checked: false },
      { value: '120', label: 'Kuwait', checked: false },
      { value: '121', label: 'Kyrgyzstan', checked: false },
      { value: '122', label: 'Laos', checked: false },
      { value: '123', label: 'Latvia', checked: false },
      { value: '124', label: 'Lebanon', checked: false },
      { value: '125', label: 'Lesotho', checked: false },
      { value: '126', label: 'Liberia', checked: false },
      { value: '127', label: 'Libya', checked: false },
      { value: '128', label: 'Liechtenstein', checked: false },
      { value: '129', label: 'Lithuania', checked: false },
      { value: '130', label: 'Luxembourg', checked: false },
      { value: '131', label: 'Macedonia', checked: false },
      { value: '132', label: 'Madagascar', checked: false },
      { value: '133', label: 'Malawi', checked: false },
      { value: '134', label: 'Malaysia', checked: false },
      { value: '135', label: 'Maldives', checked: false },
      { value: '136', label: 'Mali', checked: false },
      { value: '137', label: 'Malta', checked: false },
      { value: '138', label: 'Marshall Islands', checked: false },
      { value: '139', label: 'Martinique', checked: false },
      { value: '140', label: 'Mauritania', checked: false },
      { value: '141', label: 'Mauritius', checked: false },
      { value: '142', label: 'Mayotte', checked: false },
      { value: '143', label: 'Mexico', checked: false },
      { value: '144', label: 'Micronesia', checked: false },
      { value: '145', label: 'Moldova', checked: false },
      { value: '146', label: 'Monaco', checked: false },
      { value: '147', label: 'Mongolia', checked: false },
      { value: '148', label: 'Montenegro', checked: false },
      { value: '149', label: 'Montserrat', checked: false },
      { value: '150', label: 'Morocco', checked: false },
      { value: '151', label: 'Mozambique', checked: false },
      { value: '152', label: 'Myanmar (Burma)', checked: false },
      { value: '153', label: 'Namibia', checked: false },
      { value: '154', label: 'Nauru', checked: false },
      { value: '155', label: 'Nepal', checked: false },
      { value: '156', label: 'Netherlands', checked: false },
      { value: '157', label: 'Netherlands Antilles', checked: false },
      { value: '158', label: 'New Caledonia', checked: false },
      { value: '159', label: 'New Zealand', checked: false },
      { value: '160', label: 'Nicaragua', checked: false },
      { value: '161', label: 'Niger', checked: false },
      { value: '162', label: 'Nigeria', checked: false },
      { value: '163', label: 'Niue', checked: false },
      { value: '164', label: 'Norfolk Island', checked: false },
      { value: '165', label: 'Northern Mariana Islands', checked: false },
      { value: '166', label: 'Norway', checked: false },
      { value: '167', label: 'Oman', checked: false },
      { value: '168', label: 'Pakistan', checked: false },
      { value: '169', label: 'Palau', checked: false },
      { value: '170', label: 'Palestinian Territories', checked: false },
      { value: '171', label: 'Panama', checked: false },
      { value: '172', label: 'Papua New Guinea', checked: false },
      { value: '173', label: 'Paraguay', checked: false },
      { value: '174', label: 'Peru', checked: false },
      { value: '175', label: 'Philippines', checked: false },
      { value: '176', label: 'Pitcairn Islands', checked: false },
      { value: '177', label: 'Poland', checked: false },
      { value: '178', label: 'Portugal', checked: false },
      { value: '179', label: 'Puerto Rico', checked: false },
      { value: '180', label: 'Qatar', checked: false },
      { value: '181', label: 'Réunion', checked: false },
      { value: '182', label: 'Romania', checked: false },
      { value: '183', label: 'Russia', checked: false },
      { value: '184', label: 'Rwanda', checked: false },
      { value: '185', label: 'St. Barthélemy', checked: false },
      { value: '186', label: 'St. Helena', checked: false },
      { value: '187', label: 'St. Kitts & Nevis', checked: false },
      { value: '188', label: 'St. Lucia', checked: false },
      { value: '189', label: 'St. Martin', checked: false },
      { value: '190', label: 'St. Pierre & Miquelon', checked: false },
      { value: '191', label: 'St. Vincent & Grenadines', checked: false },
      { value: '192', label: 'Samoa', checked: false },
      { value: '193', label: 'San Marino', checked: false },
      { value: '194', label: 'São Tomé & Príncipe', checked: false },
      { value: '195', label: 'Saudi Arabia', checked: false },
      { value: '196', label: 'Senegal', checked: false },
      { value: '197', label: 'Serbia', checked: false },
      { value: '198', label: 'Seychelles', checked: false },
      { value: '199', label: 'Sierra Leone', checked: false },
      { value: '200', label: 'Singapore', checked: false },
      { value: '201', label: 'Slovakia', checked: false },
      { value: '202', label: 'Slovenia', checked: false },
      { value: '203', label: 'Solomon Islands', checked: false },
      { value: '204', label: 'Somalia', checked: false },
      { value: '205', label: 'South Africa', checked: false },
      {
        value: '206',
        label: 'South Georgia & South Sandwich Islands',
        checked: false,
      },
      { value: '207', label: 'South Sudan', checked: false },
      { value: '208', label: 'Spain', checked: false },
      { value: '209', label: 'Sri Lanka', checked: false },
      { value: '210', label: 'Sudan', checked: false },
      { value: '211', label: 'Suriname', checked: false },
      { value: '212', label: 'Svalbard & Jan Mayen', checked: false },
      { value: '213', label: 'Swaziland', checked: false },
      { value: '214', label: 'Sweden', checked: false },
      { value: '215', label: 'Switzerland', checked: false },
      { value: '216', label: 'Syria', checked: false },
      { value: '217', label: 'Taiwan', checked: false },
      { value: '218', label: 'Tajikistan', checked: false },
      { value: '219', label: 'Tanzania', checked: false },
      { value: '220', label: 'Thailand', checked: false },
      { value: '221', label: 'Timor-Leste', checked: false },
      { value: '222', label: 'Togo', checked: false },
      { value: '223', label: 'Tokelau', checked: false },
      { value: '224', label: 'Tonga', checked: false },
      { value: '225', label: 'Trinidad & Tobago', checked: false },
      { value: '226', label: 'Tunisia', checked: false },
      { value: '227', label: 'Turkey', checked: false },
      { value: '228', label: 'Turkmenistan', checked: false },
      { value: '229', label: 'Turks & Caicos Islands', checked: false },
      { value: '230', label: 'Tuvalu', checked: false },
      { value: '231', label: 'Uganda', checked: false },
      { value: '232', label: 'Ukraine', checked: false },
      { value: '233', label: 'United Arab Emirates', checked: false },
      { value: '234', label: 'United Kingdom', checked: false },
      { value: '235', label: 'United States', checked: false },
      { value: '236', label: 'U.S. Outlying Islands', checked: false },
      { value: '237', label: 'Uruguay', checked: false },
      { value: '238', label: 'Uzbekistan', checked: false },
      { value: '239', label: 'Vanuatu', checked: false },
      { value: '240', label: 'Venezuela', checked: false },
      { value: '241', label: 'Vietnam', checked: false },
      { value: '242', label: 'U.S. Virgin Islands', checked: false },
      { value: '243', label: 'Wallis & Futuna', checked: false },
      { value: '244', label: 'Western Sahara', checked: false },
      { value: '245', label: 'Yemen', checked: false },
      { value: '246', label: 'Zambia', checked: false },
      { value: '247', label: 'Zimbabwe', checked: false },
      { value: '248', label: 'Gulf Countries', checked: false },
      { value: '249', label: 'European Union', checked: false },
      { value: '250', label: 'GLOBAL', checked: false },
      { value: '251', label: 'NORTH AMERICA', checked: false },
    ],
  },
  {
    id: 'Denomination currency',
    name: 'Denomination currency',
    options: [
      { value: '', label: 'All', checked: false },
      { value: 'AED', label: 'AED', checked: false },
      { value: 'AFN', label: 'AFN', checked: false },
      { value: 'ALL', label: 'ALL', checked: false },
      { value: 'AUD', label: 'AUD', checked: false },
      { value: 'BYN', label: 'BYN', checked: false },
      { value: 'CAD', label: 'CAD', checked: false },
      { value: 'EGP', label: 'EGP', checked: false },
      { value: 'EUR', label: 'EUR', checked: false },
      { value: 'GBP', label: 'GBP', checked: false },
      { value: 'IQD', label: 'IQD', checked: false },
      { value: 'JPY', label: 'JPY', checked: false },
      { value: 'KWD', label: 'KWD', checked: false },
      { value: 'MAD', label: 'MAD', checked: false },
      { value: 'RUB', label: 'RUB', checked: false },
      { value: 'SAR', label: 'SAR', checked: false },
      { value: 'SYP', label: 'SYP', checked: false },
      { value: 'USD', label: 'USD', checked: false },
    ],
  },
];
