name: Cypress Tests

on:
  workflow_call:
    outputs:
      test_status:
        description: "Cypress Test Status"
        value: ${{ jobs.cypress-summary.outputs.test_status }}

jobs:
  # ---------------------------------
  # 1) BUILD JOB
  # ---------------------------------
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js App
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next
            # If you need other build artifacts or public folder, include them

  # ---------------------------------
  # 2) CYPRESS TEST JOB
  # ---------------------------------
  cypress-run:
    runs-on: ubuntu-24.04
    needs: build
    strategy:
      matrix:
        spec:
          - cypress/e2e/login_page_workflow.cy.js
          - cypress/e2e/orders_filter_workflow.cy.js
          - cypress/e2e/catalog_order_workflow.cy.js

    env:
      NEXT_PUBLIC_API_URL: 'https://proxy.duegate.com/staging'
      CYPRESS_apiUrl: 'https://proxy.duegate.com/staging'
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      CYPRESS_TEST_EMAIL: ${{ secrets.CYPRESS_TEST_EMAIL }}
      CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: ./.next  # Download to your .next folder

      # If you need a .env file or any other config, create it here.

      - name: Start Next.js App
        run: npm start &
        # The ampersand (&) ensures it runs in the background.
        # Make sure "start" is defined in your package.json 
        # as "next start -p 3000" or similar.

      - name: Wait for App to be Ready
        run: npx wait-on http://localhost:3000 --timeout 120000
        # Wait for up to 120 seconds

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          # Since we already built the app, do NOT rebuild here
          # we only start it above. So we can remove "build" from these inputs.
          start: false
          wait-on: false
          browser: chrome
          headed: false
          spec: ${{ matrix.spec }}
          record: true
          ci-build-id: ${{ github.run_id }}
          tag: ${{ github.sha }}

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7

  # ---------------------------------
  # 3) TEST SUMMARY JOB
  # ---------------------------------
  cypress-summary:
    runs-on: ubuntu-24.04
    needs: cypress-run
    if: always()  # Run even if Cypress tests fail
    outputs:
      test_status: ${{ steps.set-status.outputs.test_status }}
    steps:
      - name: Set Cypress Test Status
        id: set-status
        run: echo "test_status=${{ job.status }}" >> $GITHUB_ENV
