name: Cypress Tests

on:
  workflow_call:
    outputs:
      test_status:
        description: "Cypress Test Status"
        value: ${{ jobs.cypress-summary.outputs.test_status }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js App
        run: npm run build

      - name: Verify Build Output
        run: ls -lah .next  # Debugging step to confirm build directory exists

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build-${{ github.run_id }}
          path: .next  # Ensure the correct build directory

  cypress-run:
    runs-on: ubuntu-24.04
    needs: build  # Ensure Cypress runs only after the build
    strategy:
      matrix:
        spec:
          - cypress/e2e/login_page_workflow.cy.js
          - cypress/e2e/orders_filter_workflow.cy.js
          - cypress/e2e/catalog_order_workflow.cy.js

    env:
      NEXT_PUBLIC_API_URL: 'https://proxy.duegate.com/staging'
      CYPRESS_apiUrl: 'https://proxy.duegate.com/staging'
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      CYPRESS_TEST_EMAIL: ${{ secrets.CYPRESS_TEST_EMAIL }}
      CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies (Without Build)
        run: npm ci --ignore-scripts  # Install dependencies but don't rebuild

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build-${{ github.run_id }}
          path: .next  # Ensure it matches the build directory

      - name: Verify Downloaded Build
        run: ls -lah .next  # Debugging step to confirm build was downloaded

      - name: Start Next.js Server
        run: npm start &  # Start server in background

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          wait-on: 'http://localhost:3000'
          spec: ${{ matrix.spec }}
          record: true

      - name: Normalize Spec Name
        id: normalize-spec
        run: |
          SPEC_NAME=$(echo ${{ matrix.spec }} | tr '/' '_')
          echo "spec_name=$SPEC_NAME" >> $GITHUB_OUTPUT

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ steps.normalize-spec.outputs.spec_name }}
          path: cypress/screenshots
          retention-days: 7

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos-${{ steps.normalize-spec.outputs.spec_name }}
          path: cypress/videos
          retention-days: 7

  cypress-summary:
    runs-on: ubuntu-24.04
    needs: cypress-run
    if: always()  # Run even if Cypress tests fail
    outputs:
      test_status: ${{ steps.set-status.outputs.test_status }}
    steps:
      - name: Set Cypress Test Status
        id: set-status
        run: echo "test_status=${{ job.status }}" >> $GITHUB_ENV
