name: Cypress Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start application
        run: |
          npm run build
          npm start & # Run in background
        env:
          CYPRESS_BASE_URL: https://dev.b2b.hksglobal.group

      - name: Wait for application
        run: npx wait-on $CYPRESS_BASE_URL --timeout 300000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: $CYPRESS_BASE_URL
          wait-on-timeout: 300

      - name: Upload Cypress screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7
