name: Cypress Tests in Docker

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Run Application Container
        run: |
          # Build the image with the API URL set to the internal container address.
          # This ensures the app uses "http://app:3000" for API requests.
          docker build --build-arg NEXT_PUBLIC_API_URL=http://app:3000 -t radioactivehub0/b2b-arpay-v2:latest .
          docker network create cypress_network
          docker run -d --rm --network=cypress_network --name app -p 3000:3000 radioactivehub0/b2b-arpay-v2:latest
          sleep 15 # Wait for the app to be fully ready

      - name: Run Cypress Tests in a Docker Container
        run: |
          docker run --rm --network=cypress_network -v $PWD:/e2e -w /e2e cypress/included:14.0.2 \
            -e CYPRESS_apiUrl=http://app:3000 \
            cypress/included:14.0.2 \
            --config baseUrl=http://app:3000

      - name: Upload Cypress screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Stop Running Containers
        run: |
          docker stop app
          docker network rm cypress_network
