name: Cypress Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Use a stable Node.js version

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Start application
        run: |
          yarn build # If required, build the app first
          yarn start & # Start the app in the background
        env:
          CYPRESS_BASE_URL: http://localhost:3000 # This is an environment variable, not a command!

      - name: Wait for application to be ready
        run: npx wait-on $CYPRESS_BASE_URL

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          wait-on: 'http://localhost:3000' # Ensures the app is running before running tests
          wait-on-timeout: 120

      - name: Upload Cypress screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
