name: Cypress Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    env:
      # Keep NEXT_PUBLIC_API_URL as required.
      NEXT_PUBLIC_API_URL: 'https://proxy.duegate.com/staging'
      CYPRESS_apiUrl: 'https://proxy.duegate.com/staging'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'

      - name: Install Dependencies
        run: npm ci

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          config: baseUrl=http://localhost:3000
