name: Build and Push Docker Image

on:
  push:
    branches: [dev]  # Triggers when pushing to `dev`
  pull_request:
    branches: [dev]  # Triggers on PRs to `dev`

jobs:
  cypress-tests:
    uses: ./.github/workflows/cypress.yml  # Call Cypress tests workflow
    secrets: inherit  # Pass secrets from the main repo

  build-and-push:
    runs-on: ubuntu-latest
    needs: cypress-tests  # Wait for Cypress tests to complete
    if: success()  # Only run if Cypress tests passed
    env:
      NEXT_PUBLIC_API_URL: "https://proxy.duegate.com/staging"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: hub.radioactive.ac
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build --build-arg NEXT_PUBLIC_API_URL=https://proxy.duegate.com/staging -t hub.radioactive.ac/radioactive/b2b-hksglobal-group:dev .
          docker push hub.radioactive.ac/radioactive/b2b-hksglobal-group:dev

      - name: Restart Swarm Deployment
        run: |
          curl -X POST --header 'Content-Type: application/json' \
               --header 'Accept: application/json' \
               --header 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzd2FybXBpdC1hcGkiLCJleHAiOm51bGwsImlhdCI6MTcxNTMzNzM0MSwidXNyIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4ifSwianRpIjoiYjQyYzQxNDktYzdkZi00NDU2LWIzZTQtY2RmZjQ3ZDQ1NzNlIn0.8easGDbup9aOXOuTPLluxea37QQ8YFSlnJAZpiPoSXw' \
               'http://5.181.83.11:888/api/stacks/b2b-hksglobal-dev/redeploy'
